### ISSUE TITLE
Crashes immediately: undefined method `execute' for class `Class'

### ISSUE THREAD

**Issue by d3crypt3d** [Flipkart/multitenancy#2]
/var/lib/gems/1.9.1/gems/multitenancy-0.0.5/lib/multitenancy/rest_client/rest_client.rb:11:in `alias_method': undefined method`execute' for class `Class' (NameError)

from /var/lib/gems/1.9.1/gems/multitenancy-0.0.5/lib/multitenancy/rest_client/rest_client.rb:11:in `singletonclass'
        from /var/lib/gems/1.9.1/gems/multitenancy-0.0.5/lib/multitenancy/rest_client/rest_client.rb:4:in`class:Request'
        from /var/lib/gems/1.9.1/gems/multitenancy-0.0.5/lib/multitenancy/rest_client/rest_client.rb:2:in `<module:RestClient>'
        from /var/lib/gems/1.9.1/gems/multitenancy-0.0.5/lib/multitenancy/rest_client/rest_client.rb:1:in`<top (required)>'
        from /var/lib/gems/1.9.1/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /var/lib/gems/1.9.1/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in`block in require'
        from /var/lib/gems/1.9.1/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /var/lib/gems/1.9.1/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in`require'
        from /var/lib/gems/1.9.1/gems/multitenancy-0.0.5/lib/multitenancy.rb:8:in `<top (required)>'

**Comment by ganeshs** [comment]
I suspect it could be an issue with the version of rest-client. Which version of rest-client are you using?

I haven't upgraded the rest-client gem from version 1.6.7 and I suspect the latest version has this issue.

**Comment by d3crypt3d** [comment]
Right, I have 1.6.7 version been installed.
